apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motd
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd-container
        image: corentinrichard/rt903:latest
        ports:
        - containerPort: 5555
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: message
---
apiVersion: v1
kind: Service
metadata:
  name: motd-service
spec:
  type: LoadBalancer
  selector:
    app: motd
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
