apiVersion: v1
kind: Service
metadata:
  name: babystep
  namespace: max-coco-matt
spec:
  loadBalancerIP: 10.8.2.20
  ports:
  - name: http
    port: 5556
    protocol: TCP
    targetPort: 5555
  selector:
    app: babystep
  type: LoadBalancer

